import { AbilityDefinition } from './ability';

export type ArchetypeId = 'SHARDWARDEN' | 'AETHERSPARK' | 'ROOTCALLER';

export interface BaseStats {
  hp: number;
  attack: number;
  defense: number;
  speed: number;
}

export interface HeroDefinition {
  id: ArchetypeId;
  name: string;
  archetype: ArchetypeId;
  baseStats: BaseStats;
  /** The original 3 P0 abilities — kept for backward compatibility. */
  abilities: AbilityDefinition[];
  /** Full pool of all abilities available for loadout selection (8–10 per archetype). */
  abilityPool: AbilityDefinition[];
}

export const HERO_DEFINITIONS: Record<ArchetypeId, HeroDefinition> = {
  SHARDWARDEN: {
    id: 'SHARDWARDEN',
    name: 'Shardwarden',
    archetype: 'SHARDWARDEN',
    baseStats: { hp: 120, attack: 8, defense: 14, speed: 6 },
    abilities: [
      {
        id: 'fracture_wall',
        name: 'Fracture Wall',
        description: 'Creates barrier absorbing next 2 incoming attacks. If both charges consumed, deals AoE damage back (50% of absorbed).',
        type: 'DEFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'SHIELD', value: 2, target: 'SELF' }],
      },
      {
        id: 'tectonic_grip',
        name: 'Tectonic Grip',
        description: "Locks opponent's highest-cooldown ability for 2 extra turns.",
        type: 'UTILITY',
        cooldown: 5,
        resonanceCost: 3,
        effects: [{ type: 'COOLDOWN_LOCK', value: 2, duration: 2, target: 'OPPONENT' }],
      },
      {
        id: 'shard_slam',
        name: 'Shard Slam',
        description: 'ATK * 1.2 damage.',
        type: 'OFFENSIVE',
        cooldown: 2,
        resonanceCost: 1,
        effects: [{ type: 'DAMAGE', value: 1.2, target: 'OPPONENT' }],
      },
    ],
    abilityPool: [
      {
        id: 'fracture_wall',
        name: 'Fracture Wall',
        description: 'Creates barrier absorbing next 2 incoming attacks. If both charges consumed, deals AoE damage back (50% of absorbed).',
        type: 'DEFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'SHIELD', value: 2, target: 'SELF' }],
      },
      {
        id: 'tectonic_grip',
        name: 'Tectonic Grip',
        description: "Locks opponent's highest-cooldown ability for 2 extra turns.",
        type: 'UTILITY',
        cooldown: 5,
        resonanceCost: 3,
        effects: [{ type: 'COOLDOWN_LOCK', value: 2, duration: 2, target: 'OPPONENT' }],
      },
      {
        id: 'shard_slam',
        name: 'Shard Slam',
        description: 'ATK * 1.2 damage.',
        type: 'OFFENSIVE',
        cooldown: 2,
        resonanceCost: 1,
        effects: [{ type: 'DAMAGE', value: 1.2, target: 'OPPONENT' }],
      },
      {
        id: 'crystal_barrage',
        name: 'Crystal Barrage',
        description: 'Fires crystal shrapnel dealing ATK * 1.0 damage, ignoring shields.',
        type: 'OFFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'DAMAGE_IGNORE_SHIELD', value: 1.0, target: 'OPPONENT' }],
      },
      {
        id: 'seismic_pulse',
        name: 'Seismic Pulse',
        description: "Reduces opponent's ATK by 25% for 2 turns.",
        type: 'UTILITY',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'ATK_DEBUFF', value: 0.25, duration: 2, target: 'OPPONENT' }],
      },
      {
        id: 'petrify',
        name: 'Petrify',
        description: "Increases opponent's ALL cooldowns by 1 turn.",
        type: 'UTILITY',
        cooldown: 5,
        resonanceCost: 3,
        effects: [{ type: 'COOLDOWN_LOCK', value: 1, duration: 1, target: 'OPPONENT' }],
      },
      {
        id: 'stoneheart',
        name: 'Stoneheart',
        description: 'Heals 15% max HP and gains +3 DEF for 2 turns.',
        type: 'DEFENSIVE',
        cooldown: 4,
        resonanceCost: 2,
        effects: [
          { type: 'HEAL', value: 0.15, target: 'SELF' },
          { type: 'DEF_BUFF', value: 3, duration: 2, target: 'SELF' },
        ],
      },
      {
        id: 'quake_stomp',
        name: 'Quake Stomp',
        description: "Deals ATK * 1.5 damage but increases own cooldown by 1.",
        type: 'OFFENSIVE',
        cooldown: 4,
        resonanceCost: 3,
        effects: [
          { type: 'DAMAGE', value: 1.5, target: 'OPPONENT' },
          { type: 'SELF_COOLDOWN_PENALTY', value: 1, target: 'SELF' },
        ],
      },
      {
        id: 'granite_skin',
        name: 'Granite Skin',
        description: 'Reduces all incoming damage by 50% for 2 turns.',
        type: 'DEFENSIVE',
        cooldown: 6,
        resonanceCost: 3,
        effects: [{ type: 'DAMAGE_REDUCE', value: 0.5, duration: 2, target: 'SELF' }],
      },
      {
        id: 'shard_nova',
        name: 'Shard Nova',
        description: 'Deals ATK * 2.0 damage. High cost, high reward finisher.',
        type: 'OFFENSIVE',
        cooldown: 5,
        resonanceCost: 4,
        effects: [{ type: 'DAMAGE', value: 2.0, target: 'OPPONENT' }],
      },
    ],
  },
  AETHERSPARK: {
    id: 'AETHERSPARK',
    name: 'Aetherspark',
    archetype: 'AETHERSPARK',
    baseStats: { hp: 80, attack: 16, defense: 6, speed: 14 },
    abilities: [
      {
        id: 'chain_surge',
        name: 'Chain Surge',
        description: 'ATK * 1.3 damage, bonus 50% if used within 1 turn of cooldown reset.',
        type: 'OFFENSIVE',
        cooldown: 2,
        resonanceCost: 2,
        effects: [{ type: 'DAMAGE', value: 1.3, target: 'OPPONENT' }],
      },
      {
        id: 'phase_slip',
        name: 'Phase Slip',
        description: 'Dodges next attack, reduces all current cooldowns by 1.',
        type: 'UTILITY',
        cooldown: 4,
        resonanceCost: 2,
        effects: [
          { type: 'DODGE', duration: 1, target: 'SELF' },
          { type: 'COOLDOWN_REDUCE', value: 1, target: 'SELF' },
        ],
      },
      {
        id: 'spark_bolt',
        name: 'Spark Bolt',
        description: 'ATK * 0.8 damage.',
        type: 'OFFENSIVE',
        cooldown: 1,
        resonanceCost: 1,
        effects: [{ type: 'DAMAGE', value: 0.8, target: 'OPPONENT' }],
      },
    ],
    abilityPool: [
      {
        id: 'chain_surge',
        name: 'Chain Surge',
        description: 'ATK * 1.3 damage, bonus 50% if used within 1 turn of cooldown reset.',
        type: 'OFFENSIVE',
        cooldown: 2,
        resonanceCost: 2,
        effects: [{ type: 'DAMAGE', value: 1.3, target: 'OPPONENT' }],
      },
      {
        id: 'phase_slip',
        name: 'Phase Slip',
        description: 'Dodges next attack, reduces all current cooldowns by 1.',
        type: 'UTILITY',
        cooldown: 4,
        resonanceCost: 2,
        effects: [
          { type: 'DODGE', duration: 1, target: 'SELF' },
          { type: 'COOLDOWN_REDUCE', value: 1, target: 'SELF' },
        ],
      },
      {
        id: 'spark_bolt',
        name: 'Spark Bolt',
        description: 'ATK * 0.8 damage.',
        type: 'OFFENSIVE',
        cooldown: 1,
        resonanceCost: 1,
        effects: [{ type: 'DAMAGE', value: 0.8, target: 'OPPONENT' }],
      },
      {
        id: 'overload',
        name: 'Overload',
        description: 'Deals ATK * 1.0 damage.',
        type: 'OFFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'DAMAGE', value: 1.0, target: 'OPPONENT' }],
      },
      {
        id: 'mirror_image',
        name: 'Mirror Image',
        description: 'Creates a decoy — next attack has 50% chance to miss.',
        type: 'DEFENSIVE',
        cooldown: 4,
        resonanceCost: 2,
        effects: [{ type: 'MIRROR_IMAGE', value: 0.5, duration: 1, target: 'SELF' }],
      },
      {
        id: 'static_field',
        name: 'Static Field',
        description: "Deals ATK * 0.5 damage AND slows opponent's cooldown recovery by 1 for the next turn.",
        type: 'UTILITY',
        cooldown: 3,
        resonanceCost: 2,
        effects: [
          { type: 'DAMAGE', value: 0.5, target: 'OPPONENT' },
          { type: 'STAT_DEBUFF', value: 1, duration: 1, target: 'OPPONENT' },
        ],
      },
      {
        id: 'blink_strike',
        name: 'Blink Strike',
        description: 'Deals ATK * 1.1 damage and reduces own Phase Slip cooldown by 1.',
        type: 'OFFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [
          { type: 'DAMAGE', value: 1.1, target: 'OPPONENT' },
          { type: 'COOLDOWN_REDUCE', value: 1, target: 'SELF', targetAbilityId: 'phase_slip' },
        ],
      },
      {
        id: 'arcane_siphon',
        name: 'Arcane Siphon',
        description: 'Steals 2 Resonance from opponent (opponent loses 2, you gain 2).',
        type: 'UTILITY',
        cooldown: 4,
        resonanceCost: 2,
        effects: [{ type: 'RESONANCE_STEAL', value: 2, target: 'OPPONENT' }],
      },
      {
        id: 'thunderclap',
        name: 'Thunderclap',
        description: 'Deals ATK * 1.4 damage. If opponent used a DEFENSIVE ability this round, deals double.',
        type: 'OFFENSIVE',
        cooldown: 4,
        resonanceCost: 3,
        effects: [{ type: 'DAMAGE', value: 1.4, target: 'OPPONENT' }],
      },
      {
        id: 'evasive_maneuver',
        name: 'Evasive Maneuver',
        description: 'Dodges next attack AND gains +2 SPD for 3 turns.',
        type: 'DEFENSIVE',
        cooldown: 5,
        resonanceCost: 2,
        effects: [
          { type: 'DODGE', duration: 1, target: 'SELF' },
          { type: 'SPD_BUFF', value: 2, duration: 3, target: 'SELF' },
        ],
      },
    ],
  },
  ROOTCALLER: {
    id: 'ROOTCALLER',
    name: 'Rootcaller',
    archetype: 'ROOTCALLER',
    baseStats: { hp: 100, attack: 10, defense: 10, speed: 10 },
    abilities: [
      {
        id: 'verdant_mend',
        name: 'Verdant Mend',
        description: 'Heals 20% max HP. If HP below 30%, also grants regen (5% max HP per turn for 3 turns).',
        type: 'DEFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'HEAL', value: 0.2, target: 'SELF' }],
      },
      {
        id: 'entangling_bloom',
        name: 'Entangling Bloom',
        description: "Reduces opponent's next attack damage by 40%, slows their cooldown recovery by 1 turn.",
        type: 'UTILITY',
        cooldown: 4,
        resonanceCost: 3,
        effects: [
          { type: 'DAMAGE_REDUCE', value: 0.4, duration: 1, target: 'OPPONENT' },
          { type: 'STAT_DEBUFF', value: 1, duration: 1, target: 'OPPONENT' },
        ],
      },
      {
        id: 'vine_lash',
        name: 'Vine Lash',
        description: 'ATK * 1.1 damage.',
        type: 'OFFENSIVE',
        cooldown: 2,
        resonanceCost: 1,
        effects: [{ type: 'DAMAGE', value: 1.1, target: 'OPPONENT' }],
      },
    ],
    abilityPool: [
      {
        id: 'verdant_mend',
        name: 'Verdant Mend',
        description: 'Heals 20% max HP. If HP below 30%, also grants regen (5% max HP per turn for 3 turns).',
        type: 'DEFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'HEAL', value: 0.2, target: 'SELF' }],
      },
      {
        id: 'entangling_bloom',
        name: 'Entangling Bloom',
        description: "Reduces opponent's next attack damage by 40%, slows their cooldown recovery by 1 turn.",
        type: 'UTILITY',
        cooldown: 4,
        resonanceCost: 3,
        effects: [
          { type: 'DAMAGE_REDUCE', value: 0.4, duration: 1, target: 'OPPONENT' },
          { type: 'STAT_DEBUFF', value: 1, duration: 1, target: 'OPPONENT' },
        ],
      },
      {
        id: 'vine_lash',
        name: 'Vine Lash',
        description: 'ATK * 1.1 damage.',
        type: 'OFFENSIVE',
        cooldown: 2,
        resonanceCost: 1,
        effects: [{ type: 'DAMAGE', value: 1.1, target: 'OPPONENT' }],
      },
      {
        id: 'thornwall',
        name: 'Thornwall',
        description: 'Reflects 30% of next incoming damage back to attacker.',
        type: 'DEFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'DAMAGE_REFLECT', value: 0.3, duration: 1, target: 'SELF' }],
      },
      {
        id: 'spore_cloud',
        name: 'Spore Cloud',
        description: 'Poisons opponent for 3% max HP per turn for 3 turns.',
        type: 'UTILITY',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'POISON', value: 0.03, duration: 3, target: 'OPPONENT' }],
      },
      {
        id: 'bark_armor',
        name: 'Bark Armor',
        description: 'Gains damage reduction of 30% for 2 turns.',
        type: 'DEFENSIVE',
        cooldown: 4,
        resonanceCost: 2,
        effects: [{ type: 'DAMAGE_REDUCE', value: 0.3, duration: 2, target: 'SELF' }],
      },
      {
        id: 'root_slam',
        name: 'Root Slam',
        description: 'Deals ATK * 1.3 damage. If opponent is debuffed, deals 25% bonus.',
        type: 'OFFENSIVE',
        cooldown: 3,
        resonanceCost: 2,
        effects: [{ type: 'DAMAGE', value: 1.3, target: 'OPPONENT' }],
      },
      {
        id: 'natures_wrath',
        name: "Nature's Wrath",
        description: "Deals ATK * 1.8 damage but removes all active buffs from self.",
        type: 'OFFENSIVE',
        cooldown: 5,
        resonanceCost: 3,
        effects: [{ type: 'DAMAGE', value: 1.8, target: 'OPPONENT' }],
      },
      {
        id: 'rejuvenate',
        name: 'Rejuvenate',
        description: 'Removes all debuffs from self and heals 10% max HP.',
        type: 'DEFENSIVE',
        cooldown: 5,
        resonanceCost: 3,
        effects: [
          { type: 'CLEANSE', target: 'SELF' },
          { type: 'HEAL', value: 0.1, target: 'SELF' },
        ],
      },
      {
        id: 'symbiosis',
        name: 'Symbiosis',
        description: 'Heals 10% max HP AND deals ATK * 0.5 damage to opponent.',
        type: 'UTILITY',
        cooldown: 4,
        resonanceCost: 2,
        effects: [
          { type: 'HEAL', value: 0.1, target: 'SELF' },
          { type: 'DAMAGE', value: 0.5, target: 'OPPONENT' },
        ],
      },
    ],
  },
};
